name: Dance studio Swing in Rhythm
favicon: null
layout_spectrum: 0.33995
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151718'
    - '#face00'
    - '#744c00'
    - '#eaeff1'
    - '#00778d'
  brandStrength: 0.7968600622843951
  lightness: 0.3864779695868492
  saturation: 0.3564321049489081
  rhythmicContrast: 0.5402048395480961
purpose: []
